language: generic
dist: xenial
sudo: required

git:
  quiet: true

services:
  - docker
 
before_install:
  - |
    cat <<EOF  > matplotlibrc
    backend : Template
    EOF
  - cat matplotlibrc
  
  
  
script:
  - docker run -v $(pwd):/root/ --privileged --cap-add=ALL clearlinux:latest bash /root/build.sh   

before_deploy:
  - tar --exclude=.lock -zcf repo.tar.gz repo
  - git config --local user.name $GIT_USER_NAME
  - git config --local user.email $GIT_USER_EMAIL
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - repo.tar.gz
  overwrite: true
  skip_cleanup: true
